using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using UnityEngine;

namespace HMT.Puppetry {
    public enum PuppetCommandType {
        INVALID_COMMAND,
        EXECUTE_ACTION,
        EXECUTE_PLAN,
        GET_STATE,
        COMMUNICATE,
        CONFIGURE,
    }

    public enum PuppetResponseCode {
        GameIntializing = 1000,
        PuppetIntializing = 1001,
        GamePaused = 1002,

        CommandAcknowleged = 2000,
        StateRetrieved = 2001,
        GameOver = 2999,

        IllegalAction = 4000,
        InsufficientPriority = 4001,
        MissingParameters = 4002,
        BadParameters = 4003,

        CommandParseError = 5000,
        APIKeyMismatch = 5001,
        CommandNotRecognized = 5002,
        ActionNotSupportedByPuppet = 5003,
    }


    public class PuppetCommand {
        
        private const string NO_ACTION = "no_action";

        public static string ResponseCodeToStatus(int code) {
            return (code / 1000) switch {
                1 => "RESEND",
                2 => "OK",
                3 => "NOTFOUND",
                4 => "ILLEGAL",
                5 => "ERROR",
                _ => "UNKNOWN"
            };
        }

        public static HashSet<string> VALID_COMMANDS = new HashSet<string> { "execute_action", "execute_plan", "get_state", "configure", "communicate" };

        public static string CommandTypeToString(PuppetCommandType command) {
            return command switch {
                PuppetCommandType.EXECUTE_ACTION => "execute_action",
                PuppetCommandType.EXECUTE_PLAN => "execute_plan",
                PuppetCommandType.GET_STATE => "get_state",
                PuppetCommandType.COMMUNICATE => "communicate",
                PuppetCommandType.CONFIGURE => "configure",
                _ => "invalid_command"
            };
        }

        public static string FormatResponse(PuppetCommandType command, string puppetId, int code, string message, JObject content = null) {

            if(content == null)
            {
                content = new JObject();
            }
            JObject resp = new JObject
            {
                {"command", CommandTypeToString(command)},
                {"puppe_id", puppetId },
                { "code", code },
                {"status", ResponseCodeToStatus(code)  },
                {"message", message },
                {"content", content }
            };
            return resp.ToString();
        }

        private static PuppetCommandType ParseCommandType(string commandString) {
            switch (commandString.ToLower()) {
                case "execute_action":
                    return PuppetCommandType.EXECUTE_ACTION;
                case "execute_plan":
                    return PuppetCommandType.EXECUTE_PLAN;
                case "get_state":
                    return PuppetCommandType.GET_STATE;
                case "configure":
                    return PuppetCommandType.CONFIGURE;
                case "communicate":
                    return PuppetCommandType.COMMUNICATE;
                default:
                    return PuppetCommandType.INVALID_COMMAND;
            }
        }

        public const byte IDLE_PRIORITY = 255;

        public string Action { get; private set; }
        public PuppetCommandType Command { get; private set; }
        public AgentServiceConfig AgentConfig { get; private set; }
        public string TargetPuppet { get { return AgentConfig.PuppetId; } }
        public byte Priority { get { return AgentConfig.CommandPriority; } }
        public JObject Params { get; private set; }

        public List<PuppetCommand> Plan { get; private set; }

        public JObject json { get; private set; }
        public bool Responded { get; private set; }
        private HMTPuppetService originService;

        /// <summary>
        /// External Constructor used by the Puppetry Interface for commands coming from outside agents.
        /// </summary>
        /// <param name="json"></param>
        /// <param name="originService"></param>
        public PuppetCommand(JObject json, HMTPuppetService originService) {
            AgentConfig = originService.ServiceConfig;
            this.originService = originService;

            Command = ParseCommandType(json.TryGetDefault("command", string.Empty));
            Action = json.TryGetDefault("action", NO_ACTION).ToLower();
            Debug.LogFormat("<color=red>PARSE</color> json[\"params\"]: {0}  json.ToString(): {1}", json["params"], json.ToString());

            Params = json.TryGetDefault("params", new JObject());
            this.json = json;
            Responded = false;
        }

        /// <summary>
        /// Internal Action Constructor used for creating commands generated by in-game logic or player input.
        /// </summary>
        /// <param name="puppet_id"></param>
        /// <param name="action"></param>
        /// <param name="Params"></param>
        /// <param name="priority"></param>
        public PuppetCommand(string puppet_id, string action, JObject Params = null, byte priority = 128) {
            AgentConfig = new AgentServiceConfig(puppet_id, priority);
            Command = PuppetCommandType.EXECUTE_ACTION;
            Action = action;
            json = new JObject();
            this.Params = Params;
            originService = null;
            Responded = false;
        }

        /// <summary>
        /// Internal Plan Constructor used for creating commands generated by in-game logic or player input.
        /// </summary>
        /// <param name="puppet_id"></param>
        /// <param name="plan"></param>
        /// <param name="priority"></param>
        public PuppetCommand(string puppet_id, List<(string action, JObject Params)> plan, byte priority = 128) {
            AgentConfig = new AgentServiceConfig(puppet_id, priority);
            Command = PuppetCommandType.EXECUTE_PLAN;
            Action = "execute_plan";
            json = new JObject();
            Plan = new List<PuppetCommand>();
            originService = null;
            Responded = false;
            foreach (var step in plan) {
                Plan.Add(new PuppetCommand(step.action, step.Params, this));
            }
        }

        public JObject HMTStateRep() {
            JObject state = new JObject();
            state["puppet_id"] = TargetPuppet;
            state["command"] = CommandTypeToString(Command);
            state["action"] = Action;
            state["params"] = Params;
            state["priority"] = Priority;
            return state;
        }

        public T GetParam<T>(string name, T defaultValue)
        {
            if (Params != null)
            {
                return Params.TryGetDefault(name, defaultValue);
            }
            else
            {
                throw new System.Exception("no Params in Puppet Command");
            }
        }

        /// <summary>
        /// A copy constructor that is only used for creating Action commands from plan commands.
        /// </summary>
        /// <param name="action"></param>
        /// <param name="original"></param>
        private PuppetCommand(string action, JObject Params, PuppetCommand original) {
            AgentConfig = original.AgentConfig;
            Command = PuppetCommandType.EXECUTE_ACTION;
            Action = action;
            this.Params = Params;
            json = new JObject();
            originService = original.originService;
            Responded = false;
        }

        public List<PuppetCommand> GetPlan() {
            if(this.Command != PuppetCommandType.EXECUTE_PLAN) {
                return null;
            }
            if (Plan != null) {
                return Plan;
            }
            Plan = new List<PuppetCommand>();
            JToken swap;
            if (json.TryGetValue("plan", out swap)) {
                foreach (JValue planStep in swap) {
                    Plan.Add(new PuppetCommand(planStep["action"].ToString(), planStep["Params"] as JObject, this));
                }
            }
            return Plan;
        }

        //private const string RESPONSE_FORMAT = "{{\"command\":\"{0}\", \"puppet_id\":{1},  \"code\":{2}, \"status\":\"{3}\", \"message\":\"{4}\", \"content\":{5} }}";
        private void FormatAndSendResponse(int code, string message, JObject content = null) {
            if (originService == null || Responded) {
                return;
            }

            if (content == null)
            {
                content = new JObject();
            }

            JObject resp = new JObject
            {
                {"command",  CommandTypeToString(Command)},
                {"puppet_id", TargetPuppet },
                { "code", code },
                {"status", ResponseCodeToStatus(code)  },
                {"message", message },
                {"content", content }
            };


            string mess = resp.ToString();
            Debug.LogFormat("Puppet Response: {0}", mess);
            originService.Context.WebSocket.Send(mess);
            Responded = true;
        }

        #region RESEND (1000s) Responses

        public void SendGameInitializingResponse() {
            FormatAndSendResponse((int)PuppetResponseCode.GameIntializing, "Game Initializing");
        }

        public void SendPuppetInitializingResponse() {
            FormatAndSendResponse((int)PuppetResponseCode.PuppetIntializing, "Puppet Initializing");
        }

        public void SendGamePausedResponse() {
            FormatAndSendResponse((int)PuppetResponseCode.GamePaused, "Game Paused");
        }

        #endregion

        #region OK (2000s) Responses

        public void SendAcknowledgeResponse() {
            FormatAndSendResponse((int)PuppetResponseCode.CommandAcknowleged, "Command Acknowledged");
        }

        public void SendGameOverResponse() {
            FormatAndSendResponse((int)PuppetResponseCode.GameOver, "Game Over");
        }

        public void SendStateResponse(JObject state) {
            FormatAndSendResponse((int)PuppetResponseCode.StateRetrieved, "State Retrieved", state);
        }

        #endregion

        #region ILLEGAL (4000s) Responses

        public void SendIllegalActionResponse() {
            FormatAndSendResponse((int)PuppetResponseCode.IllegalAction, "Illegal Action");
        }

        public void SendIllegalActionResponse(string longMessage) {
            JObject content = new JObject {
                {"longMessage", longMessage }
            };
            FormatAndSendResponse((int)PuppetResponseCode.IllegalAction, "Illegal Action", content);
        }

        public void SendInsufficientPriorityResponse() {
            FormatAndSendResponse((int)PuppetResponseCode.InsufficientPriority, "Insufficient Priority");
        }

        public void SendMissingParametersResponse(JObject requiredParams) {
            JObject content = new JObject {
                {"requiredParams", requiredParams }
            };
            FormatAndSendResponse((int)PuppetResponseCode.MissingParameters, "Missing Parameters", content);
        }

        public void SendBadParametersResponse(JObject badParameters, JObject requiredParams) {
            JObject content = new JObject {
                {"badParams", badParameters },
                {"requiredParams", requiredParams }
            };
            FormatAndSendResponse((int)PuppetResponseCode.BadParameters, "Bad Parameters", content);
        }

        #endregion

        #region ERROR (5000s) Responses

        public void SendAPIKeyMismatchResponse() {
            FormatAndSendResponse((int)PuppetResponseCode.APIKeyMismatch, "API Key Mismatch");
        }



        public void SendCommandNotRecognizedResposne() {
            JObject content = new JObject();
            content["valid_commands"] = JArray.FromObject(VALID_COMMANDS);
            FormatAndSendResponse((int)PuppetResponseCode.CommandNotRecognized, "Command Not Recognized", content);
        }

        public void SendActionNotSupportedResponse(IEnumerable<string> supportedActions) {
            JObject content = new JObject();
            content["action_set"] = JArray.FromObject(supportedActions);
            FormatAndSendResponse((int)PuppetResponseCode.ActionNotSupportedByPuppet, "Action Not Supported By Puppet", content);
        }

        #endregion

    }
}